#!/usr/bin/ruby

Dir[__dir__ + "/**/*.rb"].each {|file| require file }

message = ARGV[0] || Bullshit::Generator.produce
translated_message = VirtualEnrique::Translator.translate(message)
human_typing = Typing.simulate(translated_message)

human_typing.each do |line|
  print "Enrique is typing..."
  #sleep(line[:typing_millis] / 1000.0)
  print "\r                    \r"
  puts "@enrique: " + line[:text] + "\n"
end

